.PHONY: test
test:
	act "pull_request" -s QUANTUM_REGISTRY_USERNAME -s QUANTUM_REGISTRY_PASSWORD

.PHONY: deploy
deploy:
	act -s QUANTUM_REGISTRY_USERNAME \
		-s QUANTUM_REGISTRY_PASSWORD \
		-s QUANTUM_USER \
		-s QUANTUM_PASSWORD \
		-s QUANTUM_ENDPOINT \
		-s QUANTUM_STACK
