---
name: ci

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: r.planetary-quantum.com
          username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
          password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}/rootfs
          file: ./${{ matrix.image }}/rootfs/Dockerfile
          push: true
          tags: r.planetary-quantum.com/quantum-public/object-storage-proxy:dev
