---
name: deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: r.planetary-quantum.com
          username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
          password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./rootfs
          file: ./rootfs/Dockerfile
          push: true
          tags: r.planetary-quantum.com/quantum-public/object-storage-proxy:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: sh
    env:
      QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
      QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
      QUANTUM_ENDPOINT: ${{ secrets.QUANTUM_ENDPOINT }}
      QUANTUM_STACK: ${{ secrets.QUANTUM_STACK }}
      QUANTUM_STORAGE_BUCKET: test-storage.staging.planetary-quantum.com
    container:
      image: r.planetary-quantum.com/quantum-public/cli:2
    steps:
      - uses: actions/checkout@v2
      - run: quantum-cli stack update --create
